# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Playwright Testing を実行してUIのパフォーマンスをテスト
- task: PlaywrightTest@1
  inputs:
    testScript: './tests/playwright/tests.js' # Playwrightテストスクリプトのパス
    browser: 'chromium'
