trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Node.jsのインストール
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # 必要に応じてNode.jsのバージョンを変更

# Playwrightのインストール
- script: |
    npm install
    npx playwright install
  displayName: 'Install dependencies and Playwright'

# Playwrightテストの実行
- script: |
    npx playwright test
  displayName: 'Run Playwright tests'

# テスト結果の発行
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-results/*.xml'
    testRunTitle: 'Playwright Tests'
