trigger:
- none

variables:
  deploymentDefaultLocation: 'japaneast'
  buildConfiguration: 'Release'
  ServiceConnectionName: 'avanadeosadatest_Tenant_Connection'
  dotnetSdkVersion: '6.x'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Analyze'
    jobs:
    - job: AnalyzeJob
      displayName: 'Analyze Job'
      steps:
        - task: NuGetToolInstaller@1

        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(solution)'

        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'SonarCloud-Connection'
            organization: 'AZ400-Book'
            scannerMode: 'MSBuild'
            projectKey: 'freeplanets_Hyperion'
            projectName: 'Hyperion'

        - task: VSBuild@1
          inputs:
            solution: '$(solution)'
            msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'

        - task: SonarCloudAnalyze@1

        - task: SonarCloudPublish@1
          inputs:
            pollingTimeoutSec: '300'
