trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'src/DemoCoreServices/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'src/DemoCoreServices/DemoCoreServices/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack the library project - $(buildConfiguration)'
  inputs:
    command: 'pack'
    projects: 'src/DemoCoreServices/DemoCoreServices/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- task: DotNetCoreCLI@2
  displayName: 'NuGet push'
  inputs:
    command: 'nuget push'
    arguments: '$(Build.ArtifactStagingDirectory)\*.nupkg --source "Hyperion/CoreService" --skip-duplicate'
