trigger:
- none

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '8.x'
  solution: '**/*.sln'
  unitTestProjects: '**/*.UnitTests/*.csproj'
  targetProjects: '**/DemoSite/*.csproj'

pool:
  vmImage: ubuntu-latest

stages:
  # Analyze
  - stage: 'Analyze'
    jobs:
    - job: AnalyzeJob
      displayName: 'Analyze Job'
      steps:
        - task: UseDotNet@2
          displayName: 'Use .NET SDK $(dotnetSdkVersion)'
          inputs:
            version: '$(dotnetSdkVersion)'
            performMultiLevelLookup: true
            includePreviewVersions: true # Required for preview versions

        - task: MicrosoftSecurityDevOps@1
          displayName: 'Microsoft Security DevOps'
          inputs:
            categories: 'secrets, code'
            break: true

  # Build
  - stage: 'Build'
    dependsOn: Analyze
    condition:  succeeded()
    displayName: 'Build the web application'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET SDK $(dotnetSdkVersion)'
            inputs:
              version: '$(dotnetSdkVersion)'
              performMultiLevelLookup: true
              includePreviewVersions: true # Required for preview versions

          - task: DotNetCoreCLI@2
            displayName: 'Restore project dependencies'
            inputs:
              command: 'restore'
              projects: $(unitTestProjects)

          - task: DotNetCoreCLI@2
            displayName: 'Build the project - $(buildConfiguration)'
            inputs:
              command: 'build'
              projects: $(unitTestProjects)
              arguments: '--no-restore --configuration $(buildConfiguration)'

  # Unit Test
  - stage: 'Test'
    displayName: 'Unit test the application'
    dependsOn: Build
    condition:  succeeded()
    jobs:
      - job: UnitTestJob
        displayName: 'UnitTest Job'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Execute unit test'
            inputs:
              command: test
              projects: $(unitTestProjects)
              arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
              publishTestResults: true

          - task: PublishCodeCoverageResults@1
            displayName: 'Publish code coverage report'
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
