
on:
  push:
    branches:
      - main
    paths:
      - '.github/bicep/**'
      
name: Deploy app service and storage
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout code
            - uses: actions/checkout@v2

            # Log into Azure
            - uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Deploy Bicep file
            - name: deploy
              id: deploy
              uses: azure/arm-deploy@v1
              with:
                  subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
                  resourceGroupName: ${{ secrets.AZURE_RG }}
                  template: .github/bicep/deploy-app-service-and-storage.bicep
                  parameters: > 
                    # prodかnonprodかを指定                   
                    environmentType=${{ secrets.ENVIRONMENT_TYPE }}
                    # ストレージアカウントをデプロイするかどうか。true/false
                    isDeployStorageAccount=${{ secrets.IS_DEPLOY_STORAGE_ACCOUNT }}                    
                  failOnStdErr: true

            # Capture and log standard error output
            - name: Output deployment logs
              if: failure()
              run: |
                echo "Deployment failed. Here are the logs:"
                cat $GITHUB_WORKSPACE/deploy.log