on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      
name: Deploy app service and storage
permissions:
  id-token: write
  contents: read
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout code
            - uses: actions/checkout@v2

            # Log into Azure
            - name: Azure login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}            

            # Deploy Bicep file
            # Specify the Bicep file path and parameters
            - name: deploy              
              uses: azure/arm-deploy@v1
              with:
                subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
                resourceGroupName: ${{ vars.AZURE_RG_NAME }}
                template: infrastructure/deploy-app-service-and-storage.bicep
                parameters: >                     
                  environmentType=${{ vars.ENVIRONMENT_TYPE }}                
                  isDeployStorageAccount=${{ vars.IS_DEPLOY_STORAGE_ACCOUNT }}                    
                failOnStdErr: false
